name: re-prods
channels:
  - defaults
dependencies:
  - python=3.10
  - scikit-learn
  - pandas
  - matplotlib
  - pyarrow
  - pip:
      - tensorflow==2.11.0
      - keras-tuner==1.3.0          
      - git+https://github.com/openai/CLIP.git